import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { stringify } from "yaml";
import { buildOpenApiDocument, countOpenApiOperations } from "./openapi/build-document.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUTPUT_PATH = path.join(ROOT, "docs", "openapi.yaml");

function main(): void {
  const checkOnly = process.argv.includes("--check");
  const document = buildOpenApiDocument();
  const yaml = stringify(document, {
    lineWidth: 120,
    sortMapEntries: false,
  });

  const header = `# Generated by pnpm openapi:generate — do not edit by hand.\n\n`;
  const output = header + yaml;

  if (checkOnly) {
    if (!fs.existsSync(OUTPUT_PATH)) {
      console.error(`Missing ${OUTPUT_PATH}. Run pnpm openapi:generate.`);
      process.exit(1);
    }
    const existing = fs.readFileSync(OUTPUT_PATH, "utf8");
    if (existing !== output) {
      console.error(
        `${OUTPUT_PATH} is out of date. Run pnpm openapi:generate and commit the result.`,
      );
      process.exit(1);
    }
    console.log(`OpenAPI spec is up to date (${countOpenApiOperations(document)} operations).`);
    return;
  }

  fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
  fs.writeFileSync(OUTPUT_PATH, output, "utf8");
  console.log(
    `Wrote ${path.relative(ROOT, OUTPUT_PATH)} (${countOpenApiOperations(document)} operations).`,
  );
}

main();
